// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaZDpmz5UEslGKKQvJWeQgxd8Qohfo39Q',
    appId: '1:947047699410:web:10181e1157b06533f66e0b',
    messagingSenderId: '947047699410',
    projectId: 'chat-app-5683d',
    authDomain: 'chat-app-5683d.firebaseapp.com',
    storageBucket: 'chat-app-5683d.appspot.com',
    measurementId: 'G-1CZB3X353D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu_zJG1l0pUlMFrNVQ5VhBFPFPDQEiVXY',
    appId: '1:947047699410:android:f0de8899266a8e62f66e0b',
    messagingSenderId: '947047699410',
    projectId: 'chat-app-5683d',
    storageBucket: 'chat-app-5683d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmh2xiOld7_K9gTFjSXQfJiUKuWzT5lpw',
    appId: '1:947047699410:ios:4258277ec69d8207f66e0b',
    messagingSenderId: '947047699410',
    projectId: 'chat-app-5683d',
    storageBucket: 'chat-app-5683d.appspot.com',
    iosClientId: '947047699410-lga3a5h18ei1242mjmi8o3e1qpth3vug.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
